Arithmetic operations are used for numerical computation and we can perform them on arrays using NumPy. With NumPy we can quickly add, subtract, multiply, divide and get power of elements in an array. NumPy performs these operations even with large amounts of data.

In [21]:
import numpy as np

a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.add(a, b)
print(res)

[  7  77  23 130]


In [22]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.subtract(a, b)
print(res)

[ 3 67  3 70]


In [23]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.multiply(a, b)
print(res)

[  10  360  130 3000]


In [24]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.divide(a, b)
print(res)

[ 2.5        14.4         1.3         3.33333333]


In [25]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.power(a, b)
print(res)

[        25 1934917632  419538377          0]


In [26]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.mod(a, b)
print(res)

[ 1  2  3 10]


In [28]:
arr = np.array([5, 10, 15])
print(np.sum(arr))

30


In [29]:
arr = np.array([20, 2, 0.2, 10, 4])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))

36.2
36
36.2


In [32]:
arr = np.array([ [14, 17, 12, 33, 44],
               [15,  6, 27,  8, 19],
               [0,2, 54,  1,  4] ])

print(np.sum(arr))
print(np.sum(arr, dtype=np.uint8))
print(np.sum(arr, dtype=np.float32))

256
0
256.0


- np.sum(arr, axis=0) column-wise sum.
- np.sum(arr, axis=1) row-wise sum.
- np.sum(arr, axis=1, keepdims=True) preserves the reduced dimension, returning a column-shaped result.

In [33]:
arr = np.array([ [14, 17, 12, 33, 44],
               [15,  6, 27,  8, 19],
               [23,  2, 54,  1,  4] ])

print(np.sum(arr))
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=1, keepdims=True))

279
[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


numpy.mean() is a NumPy function used to calculate the average (arithmetic mean) of numeric values. It can compute the mean of a 1D list/array or compute mean row-wise and column-wise for multi-dimensional arrays.

numpy.mean(arr, axis=None, dtype=None, out=None)

In [34]:
arr = [20, 2, 7, 1, 34]
res = np.mean(arr)
print(res)

12.8


In [35]:
arr = [[14, 17, 12],
       [15,  6, 27],
       [23,  2, 54]]

print(np.mean(arr))           # entire array
print(np.mean(arr, axis=0))   # column-wise mean
print(np.mean(arr, axis=1))   # row-wise mean

18.88888888888889
[17.33333333  8.33333333 31.        ]
[14.33333333 16.         26.33333333]


In [36]:
arr = [[5, 10, 15],
       [3,  6,  9],
       [8, 16, 24]]

res = np.zeros(3)
np.mean(arr, axis=1, out=res)
print(res)

[10.  6. 16.]
