NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently. It is significantly faster than Python's built-in lists because it uses optimized C language style storage where actual values are stored at contiguous locations (not object reference). It also supports vectorized computations.

- **ndarray object:** N-dimensional array for fast numerical operations.
- **Vectorized operations:** Perform element-wise calculations without loops.
- **Broadcasting:** Operate on arrays of different shapes.
- **Linear algebra functions:** Matrix operations like multiplication and inversion.
- **Statistical functions:** Mean, median, standard deviation.
- **Integration:** Works with Pandas, SciPy and scikit-learn.

**Why Learn NumPy?**
- Executes vectorized operations 10 to 100 times faster than standard Python loops.
- Uses homogeneous arrays to store large datasets more compactly than Python lists.
- Provides optimized functions for linear algebra, Fourier transforms and matrix manipulations.
- Includes robust tools for statistics, random number generation and missing data management.
- Expresses complex math in single-line commands, eliminating the need for manual, nested loops.

In [27]:
import numpy as np

a=[1,2,3,4,6,8]

print(f"original list: {a}")

arr=np.array(a)

print(f"original array: {arr}")

print(f"Type of original list: {type(a)}")

print(f"Type of original array: {type(arr)}")
    
print(f"array after adding 5: {arr+5}")

original list: [1, 2, 3, 4, 6, 8]
original array: [1 2 3 4 6 8]
Type of original list: <class 'list'>
Type of original array: <class 'numpy.ndarray'>
array after adding 5: [ 6  7  8  9 11 13]


In [28]:
# Multi dimensional array
list_1= [1,2,3]
list_2= [4,5,6]
list_3= [7,8,9]

simple_array= np.array([list_1, list_2, list_3])
print(f"Multi-dimensional array:\n{simple_array}")

print(f"shape of the array: {simple_array.shape}")

sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)


Multi-dimensional array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape of the array: (3, 3)
shape of the array : (5, 3)


In [29]:
# Rank: Rank of an array is simply the number of axes or dimensions it has.

print(f"Rank of the array arr: {arr.ndim}")
print(f"Rank of the array sample_array: {simple_array.ndim}")


Rank of the array arr: 1
Rank of the array sample_array: 2


In [30]:
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(f"3D Array:\n{arr_3d}")
print(f"Shape of 3D array: {arr_3d.shape}")
print(f"Rank of 3D array: {arr_3d.ndim}")

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of 3D array: (2, 2, 3)
Rank of 3D array: 3


In [31]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d_reshaped = arr_1d.reshape(2, 2, 3)
# Shape: (2, 2, 3)
print(arr_3d_reshaped)
print(f"Shape of reshaped 3D array: {arr_3d_reshaped.shape}")
print(f"Rank of reshaped 3D array: {arr_3d_reshaped.ndim}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape of reshaped 3D array: (2, 2, 3)
Rank of reshaped 3D array: 3


In [32]:
# Using functions like zeros() or random(): NumPy provides functions to create arrays with specific shapes filled with a single value or random values.


arr_zeros = np.zeros((3, 4))  # Creates a 3x4 array filled with zeros
print(f"Array of zeros:\n{arr_zeros}")  

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int32
Data type of array 2 : float64


*Different Ways of Creating Numpy Array*

**1. numpy.array(): Numpy array object in Numpy is called ndarray. We can create ndarray using this function.**

Syntax: numpy.array(parameter)

**2. numpy.fromiter(): The fromiter() function create a new one-dimensional array from an iterable object.**

Syntax: numpy.fromiter(iterable, dtype, count=-1)

**3. numpy.arange(): This is an inbuilt NumPy function that returns evenly spaced values within a given interval.**

Syntax:  numpy.arange( start , stop, step , dtype=None )

**4. numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.** 

Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

**5. numpy.empty(): This function create a new array of given shape and type without initializing value.**

Syntax: numpy.empty(shape, dtype=float, order='C')

**6. numpy.ones(): This function is used to get a new array of given shape and type filled with ones (1).**

Syntax: numpy.ones(shape, dtype=None, order='C')


**7. numpy.zeros(): This function is used to get a new array of given shape and type filled with zeros (0).**

Syntax: numpy.zeros(shape, dtype=None, order='C')



In [53]:
arr= np.array([1, 2, 3], dtype=np.float64)
print(f"Array with specified data type:\n{arr}")

var = "midinesh babu"
arr= np.fromiter(var, dtype='U2')
print(f"Array created from string:\n{arr}")

a = np.arange(1, 20, 2, dtype=np.float64)
np.arange(1, 20 , 2, 
          dtype = np.float32)
print(f"Array created using arange:\n{a}")

a= np.linspace(3.5, 10, 5, dtype=np.float64)
print(f"Array created using linspace:\n{a}")

empty = np.empty((2, 3), dtype=np.bool_)
print(f"Empty array:\n{empty}")

ones = np.ones((2, 3), dtype=np.int32)
print(f"Array of ones:\n{ones}")

zeros = np.zeros((2, 3), dtype=np.float64)
print(f"Array of zeros:\n{zeros}")

Array with specified data type:
[1. 2. 3.]
Array created from string:
['m' 'i' 'd' 'i' 'n' 'e' 's' 'h' ' ' 'b' 'a' 'b' 'u']
Array created using arange:
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
Array created using linspace:
[ 3.5    5.125  6.75   8.375 10.   ]
Empty array:
[[ True False False]
 [False False False]]
Array of ones:
[[1 1 1]
 [1 1 1]]
Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


In [54]:
a0 = np.zeros((2, 3))
a1 = np.ones((3, 3))
af = np.full((2, 2), 7)
ar = np.arange(0, 10, 2)  # start, stop, step
la = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",a0)
print("Ones Array:","\n",a1)
print("Constant Array:","\n",af)
print("Range Array:","\n",ar)
print("Linspace Array:","\n",la)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


**Create Python Numpy Arrays Using Random Number Generation**
NumPy provides functions to create arrays filled with random numbers.

- np.random.rand(): Creates an array of specified shape and fills it with random values sampled from a uniform distribution over [0, 1).
- np.random.randn(): Creates an array of specified shape and fills it with random values sampled from a standard normal distribution.
- np.random.randint(): Creates an array of specified shape and fills it with random integers within a given range.

In [64]:
ar = np.random.rand(2,3)  # Creates a 2x3 array with random values between 0 and 1
print(f"Random array:\n{ar}")

an= np.random.randn(2, 3)  # Creates a 2x3 array with random values from a standard normal distribution
print(f"Random array from normal distribution:\n{an}")

ai= np.random.randint(1, 10, (2, 3))  # Creates a 2x3 array with random integers between 1 and 9
print(f"Random integer array:\n{ai}")

Random array:
[[0.68453729 0.88284471 0.02891752]
 [0.01097659 0.44605732 0.80188755]]
Random array from normal distribution:
[[-0.78719969  0.14155873 -0.16223695]
 [-0.23308186  0.33757814  0.46994715]]
Random integer array:
[[5 8 2]
 [3 4 2]]


**Create Python Numpy Arrays Using Matrix Creation Routines**
NumPy provides functions to create specific types of matrices.

- np.eye(): Creates an identity matrix of specified size.
- np.diag(): Constructs a diagonal array.
- np.zeros_like(): Creates an array of zeros with the same shape and type as a given array.
- np.ones_like(): Creates an array of ones with the same shape and type as a given array.

In [68]:
im = np.eye(4)  # Creates a 4x4 identity matrix
print(f"Identity matrix:\n{im}")

da = np.diag([1, 2, 3, 4])  # Creates a diagonal array with specified values on the diagonal
print(f"Diagonal array:\n{da}")

a0 = np.zeros_like(da)
a1 = np.ones_like(da)
print(f"Array of zeros with same shape as da:\n{a0}")
print(f"Array of ones with same shape as da:\n{a1}")    

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Array of zeros with same shape as da:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Array of ones with same shape as da:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


**Numpy Array Indexing**
Array indexing in NumPy refers to the method of accessing specific elements or subsets of data within an array. This feature allows us to retrieve, modify and manipulate data at specific positions or ranges helps in making it easier to work with large datasets. In this article, we’ll see the different ways to index and slice NumPy arrays which helps us to work with our data more effectively.

**1. Accessing Elements in 1D Arrays**
A 1D NumPy array is a sequence of values with positions called indices which starts at 0. We access elements by using these indices in square brackets like arr[0] for the first element. Negative indices count from the end so arr[-1] gives the last element.

**2. Accessing Elements in Multidimensional Arrays**
In this we will see how to access elements in both 2D and 3D arrays using specific indices.

2D Arrays: We can access elements by specifying both row and column indices like matrix[row, column].

**3. Slicing Arrays**
It allows us to extract a range of elements using the format start:stop:step. This can be done for both 1D and multidimensional arrays which allows us to select ranges of elements or submatrices easily.

Slicing 1D Arrays: For a 1D array, slicing returns a subset of elements between the start and stop indices.

**4. Boolean Indexing**
It allows us to filter elements from an array based on a condition and returns only those that meet it. We create a boolean array from a condition and use it to select elements and can combine conditions with logical operators.

**5. Fancy Indexing**
It is also known as Advanced Indexing which allows us access elements of an array by using another array or list of indices. This allows selecting multiple elements at once even if they are not next to each other which makes it easy to pick specific values from different positions in the array.

**6. Integer Array Indexing**
It is similar to fancy indexing and uses an array of integers to select multiple elements from another array. This method allows us to access elements at specific, non-adjacent positions which makes it useful for extracting scattered data points.

**7. Ellipsis (...) in Indexing**
The ellipsis (...) can be used to select all dimensions which are not explicitly mentioned. This is helpful in multidimensional arrays when we don’t want to specify every dimension.

**8. Using np.newaxis to Add New Dimensions**
The np.newaxis keyword adds a new axis to the array which helps in converting a 1D array into a row or column vector.

**9. Modifying Array Elements**
We can modify array elements directly by using indexing or slicing. This makes it easy to update specific elements or ranges of elements in an array.


In [ ]:
# 1. Accessing Elements in 1D Arrays
arr= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(f"Original array:\n{arr}")

# 2. Accessing Elements in 2D Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original 2D array:\n{arr_2d}")
print(f"Element at row 1, column 2: {arr_2d[0, 1]}")  # Accessing element at first row and second column
print(f"Element at row 3, column 1: {arr_2d[2, 0]}")  # Accessing element at third row and first column

# Accessing Elements in 3D Arrays
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])      
print(f"Original 3D array:\n{arr_3d}")
print(f"Element at block 1, row 2, column 3: {arr_3d[0, 1, 2]}")  # Accessing element at first block, second row, third column
print(f"Element at block 2, row 1, column 1: {arr_3d[1, 0, 0]}")  # Accessing element at second block, first row, first column

#3. slicing arrays
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original array:\n{arr}")
print(f"Sliced array (elements from index 2 to 5):\n{arr[2:6]}")  # Slicing elements from index 2 to 5
print(f"Sliced array (every second element):\n{arr[::2]}") # Slicing every second element


#4. Boolean Indexing
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Original array:\n{arr}")
print(f"Elements greater than 5:\n{arr[arr > 5]}")  # Boolean indexing to get elements greater than 5
print(f"Elements that are even:\n{arr[arr % 2 == 0]}")  # Boolean indexing to get even elements




Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 2
Element at row 3, column 1: 7
Original 3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Element at block 1, row 2, column 3: 6
Element at block 2, row 1, column 1: 7
Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Sliced array (elements from index 2 to 5):
[3 4 5 6]
Sliced array (every second element):
[1 3 5 7 9]
Original array:
[ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5:
[ 6  7  8  9 10]
Elements that are even:
[ 2  4  6  8 10]


In [77]:
# Fancy indexing
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # Indices of the elements we want to access
print(f"Original array:\n{arr}")
print(f"Elements at indices {indices}:\n{arr[indices]}")  # Fancy indexing to access specific elements

#6. Integer Array Indexing
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(f"Original 2D array:\n{arr}")
row_indices = [0, 1, 2]  # Row indices
col_indices = [1, 0, 1]  # Column indices
print(f"Elements at specified row and column indices:\n{arr[row_indices, col_indices]}")  # Integer array indexing to access specific elements based on row and column indices  

#7. Elipsis (...) for selecting all elements along a specific axis
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"Original 3D array:\n{arr}")
print(f"All elements in the first block:\n{arr[0, ...]}")  # Using ellipsis to select all elements in the first block
print(f"All elements in the second row across all blocks:\n{arr[:, 1, :]}")  # Using ellipsis to select all elements in the second row across all blocks    
print(arr[..., 0])  # Using ellipsis to select all elements in the first column across all blocks and rows


Original array:
[10 20 30 40 50]
Elements at indices [0, 2, 4]:
[10 30 50]
Original 2D array:
[[1 2]
 [3 4]
 [5 6]]
Elements at specified row and column indices:
[2 3 6]
Original 3D array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
All elements in the first block:
[[1 2]
 [3 4]]
All elements in the second row across all blocks:
[[3 4]
 [7 8]]
[[1 3]
 [5 7]]


In [78]:
#8. np.newaxis for adding new dimensions
arr = np.array([1, 2, 3])
print(f"Original array:\n{arr}")
arr_2d = arr[:, np.newaxis]  # Adding a new axis to convert 1D array to 2D
print(f"Array after adding new axis:\n{arr_2d}")


Original array:
[1 2 3]
Array after adding new axis:
[[1]
 [2]
 [3]]


In [80]:
#9. Modifying array elements using indexing
arr = np.array([1, 2, 3, 4, 5])
print(f"Original array:\n{arr}")
arr[0] = 10  # Modifying the first element  
print(f"Array after modification:\n{arr}")
arr[1:3] = 99

print(arr)

Original array:
[1 2 3 4 5]
Array after modification:
[10  2  3  4  5]
[10 99 99  4  5]


In [86]:
arr = np.array([[10, 20, 30], [40, 5, 66], [70, 88, 94]])
print("Array:")
print(arr)

res = arr[[0,2]]
print("Accessed Rows :")
print(res)


arr = np.array([[101, 20, 3, 10], [40, 5, 66, 7], [70, 88, 9, 141]])
print("Array:")
print(arr)

res = arr[1]
print("Accessed Row :")
print(res)

res = arr[:2, :2]   # first 2 rows, first 2 columns
print("Accessed Elements:")
print(res)

Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed Rows :
[[10 20 30]
 [70 88 94]]
Array:
[[101  20   3  10]
 [ 40   5  66   7]
 [ 70  88   9 141]]
Accessed Row :
[40  5 66  7]
Accessed Elements:
[[101  20]
 [ 40   5]]


In [87]:
import numpy as np

arr = np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]], [[50, 65, 8], [70, 85, 10], [11, 22, 33]]])
print("Array:")
print(arr)

res = arr[:,[1]]
print("Accessed Rows:")
print(res)

Array:
[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]]
Accessed Rows:
[[[30 45 55]]

 [[70 85 10]]]


In [88]:
import numpy as np

arr = np.array([
    [[5, 10, 15], [20, 25, 30], [35, 40, 45]],
    [[2,  4,  6], [ 8, 10, 12], [14, 16, 18]],
    [[7, 14, 21], [28, 35, 42], [49, 56, 63]]
])
print("Array:")
print(arr)

res = arr[:, :2, :2]   # first 2 rows and first 2 columns from each 2D slice
print("Accessed Elements:")
print(res)

Array:
[[[ 5 10 15]
  [20 25 30]
  [35 40 45]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 7 14 21]
  [28 35 42]
  [49 56 63]]]
Accessed Elements:
[[[ 5 10]
  [20 25]]

 [[ 2  4]
  [ 8 10]]

 [[ 7 14]
  [28 35]]]


In [89]:
# Reshape is a powerful method in NumPy that allows you to change the shape of an array without changing its data. It is used to rearrange the elements of an array into a new shape, which can be useful for various applications such as machine learning, data analysis, and more. The reshape method takes a tuple as an argument that specifies the new shape of the array. The total number of elements in the original array must match the total number of elements in the new shape for the reshape to work correctly.
np = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_3d_reshaped = np.reshape(2, 2, 3)   
print(arr_3d_reshaped)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [90]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
r = a.reshape(3, -1)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**The numpy.stack() function is used to join multiple arrays by creating a new axis in the output array. This means the resulting array always has one extra dimension compared to the input arrays. To stack arrays, they must have the same shape, and NumPy places them along the axis you specify.

Example: This example stacks two 1D arrays along a new axis to form a 2D array.**

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))
print(np.stack((a, b), axis=-1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [92]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

y = np.array([[7, 8, 9],
              [10, 11, 12]])

print(np.stack((x, y), axis=0))
print(np.stack((x, y), axis=1))
print(np.stack((x, y), axis=2))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


Splitting arrays means dividing a single NumPy array into multiple smaller sub-arrays. NumPy provides several functions that make this easy by allowing you to split arrays along different directions (rows, columns, depth).

Below are some important terms to understand when splitting arrays:

Axis: The direction along which the array is split (0 for rows, 1 for columns).
Sub-arrays: Smaller arrays created after splitting the original array.
Splitting Methods: Functions like np.split(), np.hsplit(), np.vsplit() and np.array_split().
Equal vs. Unequal Splits: Splits can divide data evenly, or slightly unevenly if needed (using array_split()).

1. numpy.split()
numpy.split() is used to divide an array into equal-sized subarrays. The number of splits must perfectly divide the size of the array along the chosen axis. If equal division is not possible, NumPy will raise an error.

2. numpy.array_split()
numpy.array_split() works like split(), but it allows uneven splitting. This is useful when the array size does not divide evenly by the number of splits. NumPy will distribute the extra elements automatically.

3. numpy.vsplit()
numpy.vsplit() performs vertical splitting, meaning it divides a matrix row-wise (along axis=0). It works only on arrays with 2 or more dimensions.

4. numpy.hsplit()
numpy.hsplit() performs horizontal splitting, which divides the array column-wise (axis=1). This is helpful when separating feature columns in datasets.

5. numpy.dsplit()
numpy.dsplit() is used for 3D arrays. It splits the array along the third axis (axis=2). This is useful when working with stacked matrices, images, or multi-channel data.



In [98]:
import numpy as np
arr = np.arange(6)
res = np.split(arr, 2)
print(res)

arr = np.arange(13)
res = np.array_split(arr, 4)
print(res)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
res = np.vsplit(arr, 2)
print(res)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
res = np.hsplit(arr, 2)
print(res)


arr = np.arange(24).reshape((2, 3, 4))
res = np.dsplit(arr, 2)
print(res)

[array([0, 1, 2]), array([3, 4, 5])]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]
